### ISSUE TITLE
Layout grid: margin issues

### ISSUE THREAD

**Issue by simison** [Automattic/block-experiments#76] opened 2020-04-23 07:21 UTC
We've observed some breakage in production (running Gutenberg 7.8) with some homepage templates using layout grid block.

Note how it's cutting out from left side:

![image](https://user-images.githubusercontent.com/87168/80070379-8c3beb80-854b-11ea-862c-f59c83005e69.png)
![image](https://user-images.githubusercontent.com/87168/80070404-9362f980-854b-11ea-9599-b598c7550b28.png)

Looks like there are two, possibly related issues:
- when selecting the layout grid, it jumps to have different margins than when it's unselected
- when inside "full width" group block (as opposed to "wide width"), the layout grid leaks outside the canvas

Demonstration: https://cloudup.com/cj0vtSLUung

@andrewserong was wondering if it's related to the lighter Group block DOM introduced in https://github.com/WordPress/gutenberg/pull/20586

### Testing

- Start at https://wpcalypso.wordpress.com/new
- Pick e.g. Vesta template
- When landing at the editor of your new site, observe breakage

Convo p1587608359048500-slack-gutenboarding

cc @iamtakashi @ianstewart @johnHackworth

**Comment by simison** [comment] 2020-04-23 07:24
Looks like this is broken for some production page templates as well: https://cloudup.com/c4otZaFbEHF

**Comment by jasmussen** [comment] 2020-04-23 07:35
This should be fixed by #71. We were holding off on creating a new build in part due to wanting to wrap up a few additional things: 

- https://github.com/Automattic/block-experiments/issues/70
- https://github.com/Automattic/block-experiments/issues/72

- https://github.com/Automattic/block-experiments/issues/65
- https://github.com/Automattic/block-experiments/issues/64

But given circumstances, we could fasttrack an interim release. 

This issue should be present in the editor only, correct?

**Comment by simison** [comment] 2020-04-23 07:41
> This issue should be present in the editor only, correct?

Yup! Seems to affect editor and not frontend but I've done only one test with one theme:

<img width="1687" alt="image" src="https://user-images.githubusercontent.com/87168/80072431-e5f1e500-854e-11ea-86a2-faf41ce38d37.png">

**Comment by jasmussen** [comment] 2020-04-23 07:41
Cool thanks for verifying. That does strongly imply that #71 fixes it (purpose of the PR), and that releasing a new version should address this.

**Comment by simison** [comment] 2020-04-23 07:42
Excellent! :-) Is there any way I could test this already now?

**Comment by johngodley** [comment] 2020-04-23 07:54
Do you have a post I can look at? I tried https://wpcalypso.wordpress.com/new but there's nothing to press on the page.

**Comment by jasmussen** [comment] 2020-04-23 08:02
> Excellent! :-) Is there any way I could test this already now?

The way I test this is to check out and activate this block experiments repo in a local wp-env. Here's a GIF of the current status:

![grid](https://user-images.githubusercontent.com/1204802/80074454-775e5880-8549-11ea-944a-a7cbe83214c3.gif)

**Comment by simison** [comment] 2020-04-23 08:05
>so should be resilient to changing of classnames in future updates.

This is sooo much appreciated. 👍 We often need to track down and fix a lot of stuff that breaks on .com Gutenberg upgrades when relying on core's CSS classes which are far from considered stable API.

**Comment by jasmussen** [comment] 2020-04-23 11:38
Hi, thanks for the ticket. We found out that the issue happens on the layout grid block when running Gutenberg 7.8.1, and that this issue is fixed in 7.9.1. We still need to put out a new version of the plugin to improve the flow overall, but layout grid was not the cause here, so closing for the time being!

**Closed by jasmussen** 2020-04-23 11:38 UTC
Labels: bug

**Comment by alshakero** [comment] 2020-04-23 13:55
To repro, use this post HTML:

```html
<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:jetpack/layout-grid {"align":"","column1DesktopSpan":6,"column1TabletSpan":4,"column1MobileSpan":4,"column2DesktopSpan":6,"column2TabletSpan":4,"column2MobileSpan":4,"className":"column1-desktop-grid__span-6 column1-desktop-grid__row-1 column2-desktop-grid__span-6 column2-desktop-grid__start-7 column2-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2"} -->
<div class="wp-block-jetpack-layout-grid column1-desktop-grid__span-6 column1-desktop-grid__row-1 column2-desktop-grid__span-6 column2-desktop-grid__start-7 column2-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:image {"align":"full","id":448,"sizeSlug":"large"} -->
<figure class="wp-block-image alignfull size-large"><img src="https://simplepaymemts2m7cn2m7.files.wordpress.com/2018/12/pexels-photo-290538.jpeg?w=750" alt="" class="wp-image-448"/><figcaption>Photo by Pixabay on <a href="https://www.pexels.com/photo/beautiful-california-cloud-clouds-290538/" rel="nofollow">Pexels.com</a></figcaption></figure>
<!-- /wp:image --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:image {"align":"full","id":447,"sizeSlug":"large"} -->
<figure class="wp-block-image alignfull size-large"><img src="https://simplepaymemts2m7cn2m7.files.wordpress.com/2018/12/pexels-photo-457937.jpeg?w=750" alt="" class="wp-image-447"/><figcaption>Photo by Nextvoyage on <a href="https://www.pexels.com/photo/architecture-buildings-canada-city-457937/" rel="nofollow">Pexels.com</a></figcaption></figure>
<!-- /wp:image --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid --></div></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
```

**Comment by johngodley** [comment] 2020-04-23 14:04
Following up here that the problem wasn't specific to the layout grid, but is a problem with Gutenberg 7.8.1 and any full-width block that is inside a full width group.

For example:

```html
<!-- wp:group {"align":"full"} -->
<div class="wp-block-group alignfull"><div class="wp-block-group__inner-container"><!-- wp:image {"align":"full"} -->
<figure class="wp-block-image alignfull"><img alt=""/></figure>
<!-- /wp:image -->
```
