### ISSUE TITLE
Layout Grid: Changing breakpoint crashes editor

### ISSUE THREAD

**Issue by intelligence** [Automattic/block-experiments#199] opened 2021-05-26 20:13 UTC
Freshly installed via wpackagist. Created a grid and clicked "Tablet" (does the same with "Mobile") and the editor immediately crashes with these errors in the console:

```
Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at http://domain.tld/app/plugins/gutenberg/build/block-editor/index.js?ver=12eefb0b7c1cddf0756e0971095c327b:78:1551
    at Array.forEach (<anonymous>)
    at http://domain.tld/app/plugins/gutenberg/build/block-editor/index.js?ver=12eefb0b7c1cddf0756e0971095c327b:78:1507
    at commitHookEffectListMount (http://domain.tld/app/plugins/gutenberg/vendor/react-dom.82e849f1.js:19866:28)
    at commitPassiveHookEffects (http://domain.tld/app/plugins/gutenberg/vendor/react-dom.82e849f1.js:19904:13)
    at HTMLUnknownElement.callCallback (http://domain.tld/app/plugins/gutenberg/vendor/react-dom.82e849f1.js:182:16)
    at HTMLUnknownElement.dispatchEvent (<anonymous>)
    at Object.invokeGuardedCallbackDev (http://domain.tld/app/plugins/gutenberg/vendor/react-dom.82e849f1.js:231:18)
    at invokeGuardedCallback (http://domain.tld/app/plugins/gutenberg/vendor/react-dom.82e849f1.js:286:33)
    at flushPassiveEffectsImpl (http://domain.tld/app/plugins/gutenberg/vendor/react-dom.82e849f1.js:22988:11)
(anonymous) @ index.js?ver=12eefb0b7c1cddf0756e0971095c327b:78
(anonymous) @ index.js?ver=12eefb0b7c1cddf0756e0971095c327b:78
commitHookEffectListMount @ react-dom.82e849f1.js:19866
commitPassiveHookEffects @ react-dom.82e849f1.js:19904
callCallback @ react-dom.82e849f1.js:182
invokeGuardedCallbackDev @ react-dom.82e849f1.js:231
invokeGuardedCallback @ react-dom.82e849f1.js:286
flushPassiveEffectsImpl @ react-dom.82e849f1.js:22988
unstable_runWithPriority @ react.af754d50.js:2685
runWithPriority$1 @ react-dom.82e849f1.js:11174
flushPassiveEffects @ react-dom.82e849f1.js:22955
performSyncWorkOnRoot @ react-dom.82e849f1.js:21872
(anonymous) @ react-dom.82e849f1.js:11224
unstable_runWithPriority @ react.af754d50.js:2685
runWithPriority$1 @ react-dom.82e849f1.js:11174
flushSyncCallbackQueueImpl @ react-dom.82e849f1.js:11219
flushSyncCallbackQueue @ react-dom.82e849f1.js:11207
discreteUpdates$1 @ react-dom.82e849f1.js:22028
discreteUpdates @ react-dom.82e849f1.js:803
dispatchDiscreteEvent @ react-dom.82e849f1.js:4291
```

```
The above error occurred in the <Ea> component:
    in Ea (created by Gc)
    in div (created by ForwardRef)
    in div (created by ForwardRef)
    in div (created by ForwardRef)
    in div (created by ForwardRef)
    in ForwardRef (created by Gc)
    in Gc (created by Qc)
    in o (created by Qc)
    in Unknown
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(Component)
    in Tl
    in Zr
    in Zr
    in Unknown
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(Component) (created by Qc)
    in M (created by N)
    in o (created by N)
    in N (created by Qc)
    in StrictMode (created by Qc)
    in Qc

React will try to recreate this component tree from scratch using the error boundary you provided, o.
```

I'm using the Gutenberg plugin (version 10.7.1) so might be because of that?

Edit: Same with Gutenberg plugin disabled on WordPress 5.7.2

**Comment by jasmussen** [comment] 2021-05-27 06:09
Thanks for the report! I can't reproduce this on my WordPress 5.7.2 site with or without the Gutenberg 10.7.1 plugin active:

![hey](https://user-images.githubusercontent.com/1204802/119774615-b84e3c80-bec2-11eb-8130-471b53492a40.gif)

I'm not familiar with WPacackagist — have you added this block-experiments repository to it? That might be the cause of the error as there is a build process to extract and publish each block in the repository separately. Can you try installing Layout Grid from the plugin directory, and see if that causes the same issue? https://wordpress.org/plugins/layout-grid/

**Comment by intelligence** [comment] 2021-05-27 12:17
Hey! Thanks for your quick reply.

WordPress Packagist simply just syncs plugin from the plugin directory so you can handle them via Composer. But I tried pulling it manually from the directory and it still does not work. Weird!

Just removed disabled all plugins and removed all mu-plugins, and now it works, so there's something on my end causing the issue, I'll investigate further. Thanks again!

**Comment by jasmussen** [comment] 2021-05-27 12:27
Awesome, thanks for the report. I'm going to close it out on this end, but if something comes up, you can still comment and we can reopen 🚀

**Closed by jasmussen** 2021-05-27 12:27 UTC
